sequenceDiagram
    participant browser
    participant server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/spa
    activate server
    server-->>browser: HTML document
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
    activate server
    server-->>browser: The css file
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/spa.js
    activate server
    server-->>browser: The JS file
    deactivate server

    Note right of browser: The browser strarts executing js script

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/data.js
    activate server
    server-->>browser: Serves content of data.json file
    deactivate server

    Note right of browser: The browser executes function that renders notes
